export const projectsData = [
  {
    id: '1',
    title: 'Creative Agency Website',
    slug: 'creative-agency',
    description: 'A bold and modern agency website built to impress and convert visitors into clients.',
    cover_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
    category: 'web',
    hours_spent: 60,
    project_type_detail: 'Web Development',
    tags: ['React', 'TailwindCSS', 'Next.js'],
    featured: true,
    status: 'published',
  },
  {
    id: '2',
    title: 'Smart City App',
    slug: 'smart-city-app',
    description: 'Mobile solution for residents to report city issues with live tracking.',
    cover_image: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4',
    category: 'mobile',
    hours_spent: 70,
    project_type_detail: 'Mobile App Development',
    tags: ['Kotlin', 'Jetpack Compose', 'Firebase'],
    featured: true,
    status: 'published',
  },
  {
    id: '3',
    title: 'EcoWave Branding',
    slug: 'ecowave-branding',
    description: 'Sustainable brand identity project including logo, color palette, and typography.',
    cover_image: 'https://images.unsplash.com/photo-1612832021627-2b0c04d0ffcb',
    category: 'branding',
    hours_spent: 40,
    project_type_detail: 'Brand Design',
    tags: ['Illustrator', 'Figma', 'Branding'],
    featured: true,
    status: 'published',
  },
  {
    id: '4',
    title: 'Startup Dashboard',
    slug: 'startup-dashboard',
    description: 'Interactive analytics dashboard for startup founders to track growth metrics.',
    cover_image: 'https://images.unsplash.com/photo-1590608897129-79da98d1596f',
    category: 'web',
    hours_spent: 50,
    project_type_detail: 'Full Stack Web App',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    featured: false,
    status: 'published',
  },
  {
    id: '5',
    title: 'E-commerce Platform',
    slug: 'ecommerce-platform',
    description: 'A scalable online marketplace with smooth checkout and product management.',
    cover_image: 'https://images.unsplash.com/photo-1515165562835-c4c4c4c4c4c4',
    category: 'web',
    hours_spent: 90,
    project_type_detail: 'E-commerce Development',
    tags: ['Next.js', 'Stripe', 'Supabase'],
    featured: false,
    status: 'published',
  },
];
