export const projectsData = [
  {
    id: '1',
    title: 'Creative Agency Website',
    slug: 'creative-agency-website',
    description: 'A modern, responsive digital agency website featuring animations and project case studies.',
    cover_image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
    category: 'web',
    hours_spent: 48,
    project_type_detail: 'Web Development',
    tags: ['React', 'TailwindCSS', 'Framer Motion'],
  },
  {
    id: '2',
    title: 'SmartCity Mobile App',
    slug: 'smartcity-mobile-app',
    description: 'A mobile app that enables citizens to report city issues and track their resolution status.',
    cover_image: 'https://images.unsplash.com/photo-1555421689-491a97ff2040',
    category: 'mobile',
    hours_spent: 72,
    project_type_detail: 'Mobile App Development',
    tags: ['Kotlin', 'Jetpack Compose', 'Firebase'],
  },
  {
    id: '3',
    title: 'EcoWave Branding',
    slug: 'ecowave-branding',
    description: 'Complete brand identity and design system for a green tech startup.',
    cover_image: 'https://images.unsplash.com/photo-1612831455543-42eaf0bcbf1e',
    category: 'branding',
    hours_spent: 36,
    project_type_detail: 'Branding & Design',
    tags: ['Illustrator', 'Figma', 'Logo Design'],
  },
  {
    id: '4',
    title: 'AI Portfolio Builder',
    slug: 'ai-portfolio-builder',
    description: 'An AI-powered web app that generates developer portfolios instantly.',
    cover_image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786',
    category: 'web',
    hours_spent: 90,
    project_type_detail: 'Web App',
    tags: ['Next.js', 'TypeScript', 'Supabase'],
  },
  {
    id: '5',
    title: 'VR Architecture Visualizer',
    slug: 'vr-architecture-visualizer',
    description: 'A virtual reality experience to explore architectural spaces before construction.',
    cover_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
    category: '3d-printing',
    hours_spent: 120,
    project_type_detail: '3D Visualization',
    tags: ['Unity', 'C#', 'Blender'],
  },
  {
    id: '6',
    title: 'EduTrack Learning Dashboard',
    slug: 'edutrack-learning-dashboard',
    description: 'Analytics dashboard for tracking student performance and engagement across courses.',
    cover_image: 'https://images.unsplash.com/photo-1584697964191-c8f1e7f05a3b',
    category: 'ui-ux',
    hours_spent: 60,
    project_type_detail: 'UI/UX Design',
    tags: ['Figma', 'UX Research', 'Prototyping'],
  },
  {
    id: '7',
    title: 'Galaxy Defense Game',
    slug: 'galaxy-defense-game',
    description: 'A fun, space-themed arcade game built for both mobile and desktop browsers.',
    cover_image: 'https://images.unsplash.com/photo-1606813902917-87939aa3d2d3',
    category: 'game-dev',
    hours_spent: 80,
    project_type_detail: 'Game Development',
    tags: ['JavaScript', 'Phaser.js', 'Canvas API'],
  },
  {
    id: '8',
    title: 'MotionBrand Animated Ad',
    slug: 'motionbrand-animated-ad',
    description: 'A short animation created for a social media campaign to boost brand visibility.',
    cover_image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d',
    category: 'animation',
    hours_spent: 25,
    project_type_detail: '2D Animation',
    tags: ['After Effects', 'Illustrator', 'Motion Graphics'],
  },
   {
    id: '1',
    title: 'Creative Agency Website',
    slug: 'creative-agency',
    description: 'A bold and modern agency website built to impress and convert visitors into clients.',
    cover_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
    category: 'web',
    hours_spent: 60,
    project_type_detail: 'Web Development',
    tags: ['React', 'TailwindCSS', 'Next.js'],
    featured: true,
    status: 'published',
  },
  {
    id: '2',
    title: 'Smart City App',
    slug: 'smart-city-app',
    description: 'Mobile solution for residents to report city issues with live tracking.',
    cover_image: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4',
    category: 'mobile',
    hours_spent: 70,
    project_type_detail: 'Mobile App Development',
    tags: ['Kotlin', 'Jetpack Compose', 'Firebase'],
    featured: true,
    status: 'published',
  },
  {
    id: '3',
    title: 'EcoWave Branding',
    slug: 'ecowave-branding',
    description: 'Sustainable brand identity project including logo, color palette, and typography.',
    cover_image: 'https://images.unsplash.com/photo-1612832021627-2b0c04d0ffcb',
    category: 'branding',
    hours_spent: 40,
    project_type_detail: 'Brand Design',
    tags: ['Illustrator', 'Figma', 'Branding'],
    featured: true,
    status: 'published',
  },
  {
    id: '4',
    title: 'Startup Dashboard',
    slug: 'startup-dashboard',
    description: 'Interactive analytics dashboard for startup founders to track growth metrics.',
    cover_image: 'https://images.unsplash.com/photo-1590608897129-79da98d1596f',
    category: 'web',
    hours_spent: 50,
    project_type_detail: 'Full Stack Web App',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    featured: false,
    status: 'published',
  },
  {
    id: '5',
    title: 'E-commerce Platform',
    slug: 'ecommerce-platform',
    description: 'A scalable online marketplace with smooth checkout and product management.',
    cover_image: 'https://images.unsplash.com/photo-1515165562835-c4c4c4c4c4c4',
    category: 'web',
    hours_spent: 90,
    project_type_detail: 'E-commerce Development',
    tags: ['Next.js', 'Stripe', 'Supabase'],
    featured: false,
    status: 'published',
  },
];
